// Export a single chart div as PNG using Plotly's built-in toImage
export async function exportChartAsPNG(plotlyDiv, filename = 'chart') {
  const Plotly = await import('plotly.js/dist/plotly.min.js')
  const dataUrl = await Plotly.default.toImage(plotlyDiv, {
    format: 'png',
    width: 1200,
    height: 600,
    scale: 2,
  })
  const link = document.createElement('a')
  link.href = dataUrl
  link.download = `${filename}.png`
  link.click()
}


// Export a single chart as a standalone HTML file
export function exportChartAsHTML(chart, filename = 'chart') {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${chart.title}</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"><\/script>
  <style>
    body { background: #0f1117; color: #e2e8f0; font-family: system-ui, sans-serif; padding: 24px; margin: 0; }
    h2 { margin-bottom: 16px; font-size: 18px; }
    #chart { width: 100%; height: 500px; }
  </style>
</head>
<body>
  <h2>${chart.title}</h2>
  <div id="chart"></div>
  <script>
    window.addEventListener('load', function() {
      Plotly.newPlot('chart',
        ${JSON.stringify(chart.plotly_json.data)},
        ${JSON.stringify({
          ...chart.plotly_json.layout,
          paper_bgcolor: 'rgba(0,0,0,0)',
          plot_bgcolor: 'rgba(26,29,39,1)',
          font: { color: '#e2e8f0' },
          autosize: true,
        })},
        { responsive: true }
      );
    });
  <\/script>
</body>
</html>`

  downloadHTML(html, filename)
}


// Export a full dashboard as a standalone HTML file
export function exportDashboardAsHTML(dashboard) {
  const chartsHTML = dashboard.charts.map((chart, i) => `
    <div class="chart-card">
      <div class="chart-header">
        <span class="chart-num">#${chart.chart_number}</span>
        <span class="chart-title">${chart.title.replace(`Chart #${chart.chart_number} — `, '')}</span>
      </div>
      <div id="chart_${i}" style="width:100%;height:300px;"></div>
    </div>
  `).join('')

  const chartsJS = dashboard.charts.map((chart, i) => `
    Plotly.newPlot('chart_${i}',
      ${JSON.stringify(chart.plotly_json.data)},
      ${JSON.stringify({
        ...chart.plotly_json.layout,
        paper_bgcolor: 'rgba(0,0,0,0)',
        plot_bgcolor: 'rgba(15,17,23,1)',
        font: { color: '#e2e8f0', size: 11 },
        margin: { l: 40, r: 20, t: 30, b: 40 },
        autosize: true,
      })},
      { responsive: true, displayModeBar: false }
    );
  `).join('\n')

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${dashboard.title}</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"><\/script>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #0f1117; color: #e2e8f0; font-family: system-ui, sans-serif; padding: 24px; }
    h1 { font-size: 22px; margin-bottom: 8px; }
    .subtitle { color: #718096; font-size: 13px; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(480px, 1fr)); gap: 16px; }
    .chart-card { background: #1a1d27; border: 1px solid #2d3748; border-radius: 12px; padding: 16px; }
    .chart-header { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }
    .chart-num { background: rgba(59,130,246,0.2); color: #93c5fd; font-size: 11px; font-weight: bold; padding: 2px 8px; border-radius: 999px; }
    .chart-title { color: #cbd5e0; font-size: 13px; }
    .footer { margin-top: 24px; text-align: center; color: #4a5568; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${dashboard.title}</h1>
  <p class="subtitle">${dashboard.charts.length} charts · Generated by Vizora · Fully local, no cloud</p>
  <div class="grid">
    ${chartsHTML}
  </div>
  <p class="footer">Created with Vizora — fully local, privacy-first data visualization</p>
  <script>
    window.addEventListener('load', function() {
      ${chartsJS}
    });
  <\/script>
</body>
</html>`

  downloadHTML(html, dashboard.title.replace(/\s+/g, '_'))
}


export async function exportDashboardAsPDF(dashboard) {
  const Plotly = await import('plotly.js/dist/plotly.min.js')

  // Render each chart to a PNG image first using local Plotly
  const imagePromises = dashboard.charts.map(async (chart, i) => {
    const div = document.createElement('div')
    div.style.width = '800px'
    div.style.height = '400px'
    div.style.position = 'absolute'
    div.style.left = '-9999px'
    document.body.appendChild(div)

    await Plotly.default.newPlot(div, chart.plotly_json.data, {
      ...chart.plotly_json.layout,
      paper_bgcolor: '#ffffff',
      plot_bgcolor: '#f8f9fa',
      font: { color: '#1a202c', size: 11 },
      margin: { l: 40, r: 20, t: 40, b: 40 },
      autosize: false,
      width: 800,
      height: 400,
    }, { responsive: false, displayModeBar: false })

    const imgData = await Plotly.default.toImage(div, {
      format: 'png', width: 800, height: 400, scale: 1.5
    })

    Plotly.default.purge(div)
    document.body.removeChild(div)

    return {
      imgData,
      chart_number: chart.chart_number,
      title: chart.title.replace(`Chart #${chart.chart_number} — `, ''),
    }
  })

  const images = await Promise.all(imagePromises)

  const chartsHTML = images.map(img => `
    <div class="chart-card">
      <div class="chart-header">
        <span class="chart-num">#${img.chart_number}</span>
        <span class="chart-title">${img.title}</span>
      </div>
      <img src="${img.imgData}" style="width:100%;border-radius:4px;" />
    </div>
  `).join('')

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${dashboard.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #ffffff; color: #1a202c; font-family: system-ui, sans-serif; padding: 24px; }
    h1 { font-size: 20px; margin-bottom: 6px; }
    .subtitle { color: #718096; font-size: 12px; margin-bottom: 20px; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 14px; }
    .chart-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; }
    .chart-header { display: flex; align-items: center; gap: 6px; margin-bottom: 8px; }
    .chart-num { background: #ebf4ff; color: #3182ce; font-size: 10px; font-weight: bold; padding: 1px 6px; border-radius: 999px; }
    .chart-title { color: #2d3748; font-size: 12px; }
    .footer { margin-top: 20px; text-align: center; color: #a0aec0; font-size: 11px; }
    @media print { body { padding: 12px; } }
  </style>
</head>
<body>
  <h1>${dashboard.title}</h1>
  <p class="subtitle">${dashboard.charts.length} charts · Generated by Vizora</p>
  <div class="grid">${chartsHTML}</div>
  <p class="footer">Created with Vizora — fully local, privacy-first data visualization</p>
  <script>window.print();<\/script>
</body>
</html>`

  const printWindow = window.open('', '_blank')
  printWindow.document.write(html)
  printWindow.document.close()
}


function downloadHTML(html, filename) {
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${filename}.html`
  link.click()
  URL.revokeObjectURL(url)
}